### ISSUE TITLE
Unable to set all refresh rates available.

### ISSUE THREAD

**Issue by zzn3y2** [melexis-fir/mlx90641-driver-devicetree-py#1]
Only 0,1,2 and 4 can be set, no so 8, 16, 24, 32 or 64.
 In MLX90641_API.cpp we find

int MLX90641_SetRefreshRate(uint8_t slaveAddr, uint8_t refreshRate)
{
    uint16_t controlRegister1;
    int value;
    int error;
    
    value = (refreshRate & 0x07)<<7;
    
    error = MLX90641_I2CRead(slaveAddr, 0x800D, 1, &controlRegister1);
    if(error == 0)
    {
        value = (controlRegister1 & 0xFC7F) | value;
        error = MLX90641_I2CWrite(slaveAddr, 0x800D, value);
    }    
    
    return error;
}

line: value = (refreshRate & 0x07)<<7; don't seem to be implemented for values above 7

**Comment by mlx-kva** [comment]
Hello Marco,

With this driver we follow the embedded c library API.
The c lib you can find here:
https://github.com/melexis/mlx90641-library

0 => 0.5 fps
1 => 1 fps
2 => 2 fps
3 => 4 fps
4 => 8 fps
5 => 16 fps
6 => 32 fps
7 => 64 fps

Thanks,
Karel.
